### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by webianks** [webianks/BreathingProgressDemo#2]
Update Read Me to add pull request

**Comment by anubhakushwaha** [comment]
@webianks You meant giving instructions to users on how to fork the project ,study it and create a PR?
Further wasn't the issue to be tagged with hactoberfest rather than naming the issue with one.Apologies incase I am wrong anywhere.

**Comment by anubhakushwaha** [comment]
#4 Done.
Added:
1.Setup for Developers
2.Configuring remotes
3.Contributing and developing a feature

**Comment by webianks** [comment]
Okay cool !!
